theme: jekyll-theme-cayman

title: Robotit Strömbergin puistossa
date_and_time: 10.6.2017 klo 14-16
description: Pienoisrobottien kisa Pitäjänmäessä

fb_event_number: 1165421916919554

twitter_image: ""
twitter_account: "@HelsinkiHacklab"

og_url: "http://robotit.hacklab.fi"
og_image: ""
