theme: jekyll-theme-cayman

title: Robotit Strömbergin puistossa
date_and_time: 10.6.2017 klo 14-16
this_year: 2017
description: Pienoisrobottien kisa Pitäjänmäessä

fb_event_number: 1165421916919554

twitter_image: "/media/images/tw_robotti.png"
twitter_account: "@HelsinkiHacklab"

og_url: "http://robotit.hacklab.fi"
og_image: "/media/images/tw_robotti.png"
og_image_width: "440"
og_image_height: "440"
og_image_type: "image/png"

social_media_description: "Pienet robotit kisaavat sokkeloradalla ja törmäilevät seiniin. Kuka pääsee maaliin asti? Ilmainen koko perheen tapahtuma Pitskussa."
