theme: jekyll-theme-cayman
markdown: kramdown

plugins:
  - jekyll-default-layout

title: Robotit Strömbergin puistossa
date_and_time: 15.6.2019 klo 16-17.30

# Meta-kuvauksiin:
start_ISO8601: 2019-06-15T1600
end_ISO8601: 2019-06-15T1730

# Minkä vuoden tietoja sivulla esitetään
this_year: 2019
description: Pienoisrobottien kisa Pitäjänmäessä Helsingissä


# Jos on tiedossa tapahtuman FB-sivu:
#fb_event_number: 1165421916919554
#fb_event_number: 595385874156556
fb_event_number: 821540898226172

twitter_image: "/media/images/tw_robotti.png"
twitter_account: "@HelsinkiHacklab"

og_url: "http://robotit.hacklab.fi"
og_image: "/media/images/tw_robotti.png"
og_image_width: "440"
og_image_height: "440"
og_image_type: "image/png"

social_media_description: "Pienet robotit kisaavat sokkeloradalla ja törmäilevät seiniin. Kuka pääsee maaliin asti? Ilmainen koko perheen tapahtuma Pitskussa."


# Pika-asetukset nopeaan muokkaamiseen
# Jos on tiedossa sadetta, laita tähän true
possible_rain: false
# Laita true tähän, kun seuraavaan tapahtuma on vasta pitkän ajan kuluttua:
see_you_in_next_event: false
# Näytä Taiken logo
taike: true
